name: Java CI 

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        name: Git Clone
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JavaVersion }} 
      - name: Gradle
        run: ./gradlew build
      
  
